"""
Asset-specific detection rule generator.
Reads asset DB and generates a comprehensive set of asset-specific rules
including behavior-baselined anomaly, geo, JA3/JA4, MAC, and time rules.
SID range: 1000300-1001999 (reserved for auto-generated asset rules).
"""

import os
import re
from datetime import datetime
from db import get_db
from analyzers.asset_baseline import load_baselines


# SID base for auto-generated rules
BASE_SID = 1000300

# Detection engine config path - read once to check optional features
ENGINE_CONFIG = os.environ.get("SURICATA_YAML", "/etc/suricata/suricata.yaml")


def _engine_has_geoip():
    """Check whether the detection engine has a GeoIP database configured."""
    try:
        with open(ENGINE_CONFIG, "r") as f:
            content = f.read()
        # Look for active (uncommented) geoip-database directive
        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            if "geoip-database" in stripped or "geoip2-database" in stripped:
                # Check it has a value (not just the key)
                if ":" in stripped:
                    val = stripped.split(":", 1)[1].strip()
                    if val and val not in ("''", '""'):
                        return True
        return False
    except (IOError, PermissionError):
        return False


def _engine_supports_ether():
    """Check engine version for ether.src keyword support (7.0+)."""
    try:
        import subprocess
        out = subprocess.run(["suricata", "-V"], capture_output=True, text=True, timeout=2)
        m = re.search(r"version\s+(\d+)\.", out.stdout)
        if m:
            return int(m.group(1)) >= 7
    except Exception:
        pass
    return False


# Cache feature support at import time
_HAS_GEOIP = None
_HAS_ETHER = None


def feature_support():
    """Returns dict of available optional features."""
    global _HAS_GEOIP, _HAS_ETHER
    if _HAS_GEOIP is None:
        _HAS_GEOIP = _engine_has_geoip()
    if _HAS_ETHER is None:
        _HAS_ETHER = _engine_supports_ether()
    return {"geoip": _HAS_GEOIP, "ether": _HAS_ETHER}


def reset_feature_cache():
    """Force re-detection of optional features (call after config changes)."""
    global _HAS_GEOIP, _HAS_ETHER
    _HAS_GEOIP = None
    _HAS_ETHER = None

# Header for the generated section
GENERATED_HEADER = """
# ============================================================================
# AUTO-GENERATED ASSET-SPECIFIC RULES
# Generated by Notice rule_generator
# DO NOT EDIT MANUALLY - regenerate via /api/monitoring/regenerate-rules
# ============================================================================
"""

# Marker to find and replace generated section
GENERATED_START = "# === BEGIN AUTO-GENERATED ASSET RULES ==="
GENERATED_END = "# === END AUTO-GENERATED ASSET RULES ==="


def generate_rules_for_asset(asset, sid_start, baseline=None):
    """Generate a comprehensive rule set for one asset. Returns (rules_list, next_sid).

    Args:
        asset: dict with ip/owner/asset_type/business_critical
        sid_start: starting SID number for this asset
        baseline: optional dict from asset_baseline (listening_ports, ja3_hashes,
                  ja4_hashes, dest_countries, mac_address, peak_flows_per_min,
                  active_hours, etc.) — when provided, generates richer rules
    """
    ip = asset["ip"]
    owner = asset.get("owner", "") or "unowned"
    atype = asset.get("asset_type", "workstation") or "workstation"
    critical = asset.get("business_critical", 0)
    notes = asset.get("notes", "") or ""

    sid = sid_start
    rules = []
    severity = "Critical" if critical else "Major"
    confidence = "High" if critical else "Medium"

    label = f"[{owner}]" if owner != "unowned" else ""
    crit_tag = " [CRITICAL]" if critical else ""

    # Common metadata fragment
    meta = f"metadata:created_at {datetime.now().strftime('%Y_%m_%d')}, signature_severity {severity}, deployment Internal, confidence {confidence};"

    # ─── Rule 1: External SSH brute force to this asset ───
    rules.append(
        f'alert tcp $EXTERNAL_NET any -> {ip} 22 '
        f'(msg:"NOTICE ASSET{crit_tag} External SSH Brute Force to {ip} {label}"; '
        f'flow:to_server; flags:S; threshold:type both, track by_src, count 5, seconds 60; '
        f'classtype:attempted-admin; sid:{sid}; rev:1; {meta})'
    )
    sid += 1

    # ─── Rule 2: Internal port scan against this asset ───
    rules.append(
        f'alert tcp $HOME_NET any -> {ip} any '
        f'(msg:"NOTICE ASSET{crit_tag} Internal Port Scan against {ip} {label}"; '
        f'flow:to_server; flags:S,12; threshold:type both, track by_src, count 15, seconds 60; '
        f'classtype:attempted-recon; sid:{sid}; rev:1; {meta})'
    )
    sid += 1

    # ─── Rule 3: External port scan against this asset ───
    rules.append(
        f'alert tcp $EXTERNAL_NET any -> {ip} any '
        f'(msg:"NOTICE ASSET{crit_tag} External Port Scan against {ip} {label}"; '
        f'flow:to_server; flags:S,12; threshold:type both, track by_src, count 10, seconds 60; '
        f'classtype:attempted-recon; sid:{sid}; rev:1; {meta})'
    )
    sid += 1

    # ─── Rule 4: Excessive outbound connections from this asset (data exfil) ───
    rules.append(
        f'alert tcp {ip} any -> $EXTERNAL_NET any '
        f'(msg:"NOTICE ASSET{crit_tag} Excessive Outbound Connections from {ip} {label} - Possible Exfil/C2"; '
        f'flow:to_server,established; threshold:type both, track by_src, count 100, seconds 60; '
        f'classtype:trojan-activity; sid:{sid}; rev:1; {meta})'
    )
    sid += 1

    # ─── Rule 5: Suspicious DNS queries from this asset (tunneling) ───
    rules.append(
        f'alert dns {ip} any -> any 53 '
        f'(msg:"NOTICE ASSET{crit_tag} High-Volume DNS Queries from {ip} {label} - Possible Tunneling"; '
        f'threshold:type both, track by_src, count 200, seconds 60; '
        f'classtype:bad-unknown; sid:{sid}; rev:1; {meta})'
    )
    sid += 1

    # ─── Server-specific rules ───
    if atype == "server":
        # Inbound on RDP
        rules.append(
            f'alert tcp $EXTERNAL_NET any -> {ip} 3389 '
            f'(msg:"NOTICE ASSET{crit_tag} External RDP Connection to Server {ip} {label}"; '
            f'flow:to_server,established; threshold:type limit, track by_src, count 1, seconds 300; '
            f'classtype:attempted-admin; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

        # SMB access from external
        rules.append(
            f'alert tcp $EXTERNAL_NET any -> {ip} [445,139] '
            f'(msg:"NOTICE ASSET{crit_tag} External SMB Access to Server {ip} {label} - Should Never Happen"; '
            f'flow:to_server,established; '
            f'classtype:attempted-admin; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

        # Database port access from non-server hosts
        rules.append(
            f'alert tcp $EXTERNAL_NET any -> {ip} [3306,1433,5432,1521,27017,6379] '
            f'(msg:"NOTICE ASSET{crit_tag} External Database Connection Attempt to Server {ip} {label}"; '
            f'flow:to_server; flags:S; '
            f'classtype:attempted-admin; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

        # HTTP attack patterns inbound
        rules.append(
            f'alert http $EXTERNAL_NET any -> {ip} any '
            f'(msg:"NOTICE ASSET{crit_tag} HTTP Attack Pattern to Server {ip} {label}"; '
            f'flow:to_server,established; http.uri; '
            f'pcre:"/(union\\s+select|\\.\\./|<script|eval\\(|/etc/passwd|cmd\\.exe|whoami)/i"; '
            f'classtype:web-application-attack; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

    # ─── Workstation-specific rules ───
    if atype == "workstation":
        # Workstations shouldn't accept inbound from external
        rules.append(
            f'alert tcp $EXTERNAL_NET any -> {ip} any '
            f'(msg:"NOTICE ASSET{crit_tag} Inbound External Connection to Workstation {ip} {label} - Unusual"; '
            f'flow:to_server,established; threshold:type both, track by_dst, count 3, seconds 300; '
            f'classtype:misc-activity; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

        # Workstation outbound to non-standard ports (potential C2)
        rules.append(
            f'alert tcp {ip} any -> $EXTERNAL_NET ![80,443,53,123,8080,8443] '
            f'(msg:"NOTICE ASSET{crit_tag} Workstation {ip} {label} Connection to Non-Standard External Port"; '
            f'flow:to_server,established; threshold:type both, track by_src, count 10, seconds 300; '
            f'classtype:misc-activity; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

    # ─── Critical asset bonus rules ───
    if critical:
        # Any TLS connection from critical asset to non-standard port
        rules.append(
            f'alert tls {ip} any -> $EXTERNAL_NET ![443,8443,993,995,465,587] '
            f'(msg:"NOTICE ASSET [CRITICAL] {ip} {label} TLS to Non-Standard Port - Possible C2"; '
            f'flow:to_server,established; '
            f'classtype:trojan-activity; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

        # Any plaintext credential-bearing protocol from critical asset
        rules.append(
            f'alert tcp {ip} any -> any [21,23,80,110,143] '
            f'(msg:"NOTICE ASSET [CRITICAL] {ip} {label} Plaintext Protocol Use - Policy Violation"; '
            f'flow:to_server,established; threshold:type limit, track by_src, count 1, seconds 600; '
            f'classtype:policy-violation; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

        # Any large outbound flow from critical asset
        rules.append(
            f'alert tcp {ip} any -> $EXTERNAL_NET any '
            f'(msg:"NOTICE ASSET [CRITICAL] {ip} {label} Large Outbound Transfer - Possible Exfil"; '
            f'flow:to_server,established; flowbits:noalert; dsize:>10000; '
            f'threshold:type both, track by_src, count 50, seconds 60; '
            f'classtype:policy-violation; sid:{sid}; rev:1; {meta})'
        )
        sid += 1

    # ════════════════════════════════════════════════════════════════════
    # BASELINE-DRIVEN RULES (only if baseline data available)
    # ════════════════════════════════════════════════════════════════════
    feats = feature_support()
    if baseline:
        # ─── Anomaly: traffic-rate deviation ───
        peak = baseline.get("peak_flows_per_min", 0)
        if peak > 0:
            # Alert when flow rate is 2.5x the historic peak (anomaly threshold)
            anomaly_threshold = max(50, int(peak * 2.5))
            rules.append(
                f'alert ip {ip} any -> any any '
                f'(msg:"NOTICE ASSET{crit_tag} ANOMALY {ip} {label} Flow Rate >{anomaly_threshold}/min (baseline peak {peak})"; '
                f'threshold:type both, track by_src, count {anomaly_threshold}, seconds 60; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, signature_severity {severity}, '
                f'deployment Internal, confidence {confidence}, baseline_peak {peak};)'
            )
            sid += 1

        # ─── Service-specific: rules for each observed listening port ───
        for port in baseline.get("listening_ports", [])[:5]:  # top 5 ports
            # External connections to known service port (legitimate, but log)
            rules.append(
                f'alert tcp $EXTERNAL_NET any -> {ip} {port} '
                f'(msg:"NOTICE ASSET{crit_tag} SERVICE {ip} {label} External Connection to Known Service Port {port}"; '
                f'flow:to_server,established; threshold:type both, track by_src, count 20, seconds 60; '
                f'classtype:not-suspicious; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity Minor, deployment Internal, confidence Medium, baseline_port {port};)'
            )
            sid += 1
            # Connection to NON-listening ports (potential service abuse)
        if baseline.get("listening_ports"):
            ports_csv = ",".join(str(p) for p in baseline["listening_ports"][:8])
            rules.append(
                f'alert tcp any any -> {ip} ![{ports_csv},22,53,123,135,139,445,5353] '
                f'(msg:"NOTICE ASSET{crit_tag} SERVICE {ip} {label} Connection to Non-Baseline Port (baseline: {ports_csv})"; '
                f'flow:to_server,established; threshold:type both, track by_dst, count 5, seconds 120; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Internal, confidence Medium;)'
            )
            sid += 1

        # ─── Time-based: off-hours activity ───
        # Off hours = hours OUTSIDE 09:00–19:00 IST that ARE active in baseline
        # We use the daterange/lua approach is unsupported here, so we generate
        # a low-threshold rule tagged as off-hours-intent and rely on analyst review.
        if atype == "workstation":
            rules.append(
                f'alert tcp {ip} any -> $EXTERNAL_NET any '
                f'(msg:"NOTICE ASSET{crit_tag} OFFHOURS {ip} {label} Workstation External Activity (review timestamp - flag if 22:00-06:00)"; '
                f'flow:to_server,established; threshold:type both, track by_src, count 30, seconds 600; '
                f'classtype:policy-violation; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity Minor, deployment Internal, confidence Low, off_hours_intent yes;)'
            )
            sid += 1

        # ─── Geographic: alert on connections from countries outside baseline ───
        # Only emit if engine has a GeoIP database loaded
        countries = baseline.get("dest_countries", [])
        if countries and feats["geoip"]:
            # Generate negation list: top 5 countries this asset normally talks to
            top_5 = countries[:5]
            geo_negation = ",".join(f"!{cc}" for cc in top_5)
            rules.append(
                f'alert ip $EXTERNAL_NET any -> {ip} any '
                f'(msg:"NOTICE ASSET{crit_tag} GEO {ip} {label} Inbound from Unusual Country (baseline: {",".join(top_5)})"; '
                f'geoip:src,{geo_negation}; flow:to_server,established; '
                f'threshold:type both, track by_src, count 3, seconds 300; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Perimeter, confidence Medium, requires geoip_database;)'
            )
            sid += 1
            # Also alert on outbound connections to unusual countries
            rules.append(
                f'alert ip {ip} any -> $EXTERNAL_NET any '
                f'(msg:"NOTICE ASSET{crit_tag} GEO {ip} {label} Outbound to Unusual Country (baseline: {",".join(top_5)})"; '
                f'geoip:dst,{geo_negation}; flow:to_server,established; '
                f'threshold:type both, track by_src, count 5, seconds 300; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Perimeter, confidence Medium, requires geoip_database;)'
            )
            sid += 1

        # ─── JA3 fingerprint pinning ───
        # Combine all baseline hashes into a single PCRE negation (avoids duplicate-buffer warnings)
        ja3_list = baseline.get("ja3_hashes", [])
        if ja3_list and atype == "server":
            top_ja3 = ja3_list[:8]
            # Escape any regex specials (hashes are hex, but be safe) and build one alternation
            ja3_alt = "|".join(re.escape(h) for h in top_ja3)
            rules.append(
                f'alert tls $EXTERNAL_NET any -> {ip} any '
                f'(msg:"NOTICE ASSET{crit_tag} TLS-FP {ip} {label} New JA3 Fingerprint - Not in {len(top_ja3)}-hash Baseline"; '
                f'flow:to_server,established; ja3.hash; pcre:!"/^({ja3_alt})$/"; '
                f'threshold:type both, track by_src, count 1, seconds 600; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Internal, confidence Medium, '
                f'baseline_ja3_count {len(ja3_list)};)'
            )
            sid += 1

        # ─── JA4 fingerprint pinning (uses ja4.hash keyword, not ja4) ───
        ja4_list = baseline.get("ja4_hashes", [])
        if ja4_list and atype == "server":
            top_ja4 = ja4_list[:8]
            ja4_alt = "|".join(re.escape(h) for h in top_ja4)
            rules.append(
                f'alert tls $EXTERNAL_NET any -> {ip} any '
                f'(msg:"NOTICE ASSET{crit_tag} TLS-FP {ip} {label} New JA4 Fingerprint - Not in {len(top_ja4)}-hash Baseline"; '
                f'flow:to_server,established; ja4.hash; pcre:!"/^({ja4_alt})$/"; '
                f'threshold:type both, track by_src, count 1, seconds 600; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Internal, confidence Medium, '
                f'baseline_ja4_count {len(ja4_list)};)'
            )
            sid += 1

        # ─── DHCP/MAC consistency ───
        # ether.src requires detection engine 7.0+
        mac = baseline.get("mac_address")
        if mac and feats["ether"]:
            # Alert when this IP is associated with a different MAC than the baseline
            rules.append(
                f'alert ip {ip} any -> any any '
                f'(msg:"NOTICE ASSET{crit_tag} MAC {ip} {label} IP Associated with Non-Baseline MAC (baseline: {mac})"; '
                f'ether.src; content:!"|{mac.replace(":"," ")}|"; '
                f'threshold:type both, track by_src, count 1, seconds 3600; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Internal, confidence High, '
                f'baseline_mac {mac.replace(":","-")};)'
            )
            sid += 1
        # DHCP-based MAC change detection works on any version
        if mac:
            rules.append(
                f'alert dhcp any any -> any any '
                f'(msg:"NOTICE ASSET{crit_tag} MAC {ip} {label} DHCP Reassignment - IP Bound to New MAC"; '
                f'dhcp.assigned_ip; content:"{ip}"; '
                f'threshold:type limit, track by_dst, count 1, seconds 60; '
                f'classtype:misc-activity; sid:{sid}; rev:1; '
                f'metadata:created_at {datetime.now().strftime("%Y_%m_%d")}, '
                f'signature_severity {severity}, deployment Internal, confidence Medium, '
                f'baseline_mac {mac.replace(":","-")};)'
            )
            sid += 1

    return rules, sid


def generate_all_asset_rules():
    """Generate rules for all internal assets in the DB. Uses behavioral
    baselines if available (run /api/monitoring/refresh-baseline first)."""
    conn = get_db()
    assets = [dict(r) for r in conn.execute(
        "SELECT * FROM assets WHERE scope='internal' ORDER BY business_critical DESC, ip"
    ).fetchall()]
    conn.close()

    # Load asset baselines (may be empty if not yet computed)
    baselines = load_baselines()
    baseline_count = sum(1 for ip in (a["ip"] for a in assets) if ip in baselines)
    feats = feature_support()

    all_rules = [GENERATED_START]
    all_rules.append(f"# Generated: {datetime.now().isoformat()}")
    all_rules.append(f"# Total assets: {len(assets)}")
    all_rules.append(f"# Assets with behavioral baseline: {baseline_count}/{len(assets)}")
    all_rules.append(f"# Baseline categories: anomaly, service, time, ja3/ja4, dhcp")
    all_rules.append(f"# Optional features: geoip={'enabled' if feats['geoip'] else 'DISABLED (no GeoIP DB configured)'}, ether={'enabled' if feats['ether'] else 'DISABLED (engine <7.0)'}")
    all_rules.append("")

    sid = BASE_SID
    rules_per_asset = {}
    baseline_rule_count = 0
    for asset in assets:
        ip = asset["ip"]
        baseline = baselines.get(ip)
        before_sid = sid
        rules, sid = generate_rules_for_asset(asset, sid, baseline=baseline)
        rules_per_asset[ip] = len(rules)
        if baseline:
            # Count baseline-driven rules (everything beyond the static set)
            base_rules = 5 + (4 if asset.get("asset_type") == "server" else 2 if asset.get("asset_type") == "workstation" else 0) + (3 if asset.get("business_critical") else 0)
            baseline_rule_count += max(0, len(rules) - base_rules)

        baseline_tag = " [+baseline]" if baseline else ""
        all_rules.append(f"\n# --- Asset: {ip} ({asset.get('owner','')} - {asset.get('asset_type','')}){baseline_tag} ---")
        all_rules.extend(rules)

    all_rules.append("")
    all_rules.append(GENERATED_END)
    return "\n".join(all_rules), {
        "total_rules": sid - BASE_SID,
        "total_assets": len(assets),
        "baselined_assets": baseline_count,
        "baseline_driven_rules": baseline_rule_count,
        "rules_per_asset": rules_per_asset,
        "sid_range": f"{BASE_SID}-{sid - 1}",
        "feature_support": feats,
        "skipped_categories": (
            (["geographic"] if not feats["geoip"] else []) +
            (["mac (ether.src)"] if not feats["ether"] else [])
        ),
    }


def write_rules_to_file(rules_path="/var/lib/suricata/rules/local.rules"):
    """Append (or replace) the generated section in local.rules."""
    new_content, stats = generate_all_asset_rules()

    if not os.path.exists(rules_path):
        return {"error": f"Rules file not found: {rules_path}", "stats": stats}

    try:
        with open(rules_path, "r") as f:
            existing = f.read()
    except (IOError, PermissionError) as e:
        return {"error": f"Cannot read rules file: {e}", "stats": stats}

    # Update IP lists in manual rules that reference asset groups
    conn = get_db()
    db_ips = [r["ip"] for r in conn.execute(
        "SELECT ip FROM assets WHERE scope='internal' ORDER BY ip"
    ).fetchall()]
    conn.close()
    if db_ips:
        ip_group = "[" + ",".join(db_ips) + "]"
        import re
        existing = re.sub(
            r'\[(?:\d+\.\d+\.\d+\.\d+,?)+\](\s+(?:22|any)\s+\(msg:"NOTICE (?:ASSET|SCAN))',
            lambda m: ip_group + m.group(1),
            existing,
        )

    # Find existing section to replace
    if GENERATED_START in existing and GENERATED_END in existing:
        before = existing.split(GENERATED_START)[0].rstrip()
        after_start = existing.split(GENERATED_END, 1)
        after = after_start[1] if len(after_start) > 1 else ""
        merged = before + "\n\n" + new_content + "\n" + after
    else:
        # Append at end
        merged = existing.rstrip() + "\n\n" + new_content + "\n"

    try:
        with open(rules_path, "w") as f:
            f.write(merged)
    except (IOError, PermissionError) as e:
        return {"error": f"Cannot write rules file: {e}", "stats": stats}

    # Invalidate rule caches
    from analyzers import suricata_rules
    suricata_rules._RULE_STATS_CACHE = None
    suricata_rules._RULE_STATS_MTIME = 0
    try:
        from analyzers.rule_coverage import _clear_cache
        _clear_cache()
    except Exception:
        pass

    return {
        "ok": True,
        "stats": stats,
        "path": rules_path,
        "note": "Reload the detection engine for these rules to take effect.",
    }
